### ISSUE TITLE
Race condition with "System.Diagnostics.TraceInternal.WriteLine" - GarbageMan.cs

### ISSUE THREAD

**Issue by ricjac** [NimbusAPI/Nimbus#242]
From the stack trace below the exception occurs here: [GarbageMan.cs L18](https://github.com/NimbusAPI/Nimbus/blob/e99743f343cd6ba6f1dd3e085f581082761a972a/src/Nimbus/Configuration/PoorMansIocContainer/GarbageMan.cs#L18)
The line is: `Trace.WriteLine("Tracking {0}......`

We've had this issue before when compiling/running our application with 'Release' configuration.
But now we are noticing this issue on one of two machines which _should_ be identical.

Any clues as to what it could be? What to check?

> Error "sending" "GetPackageItemCommand" (15d848a7-221f-440f-a4a5-6a4f21c4240c) to "q.gsf.provider.landata.common.v1.command.getpackageitemcommand" (MessageMetadata { MessageId: 15d848a7-221f-440f-a4a5-6a4f21c4240c, CorrelationId: ffa7d77f-8bda-4c9b-9421-973fba2d83d0, ShortMessageTypeName: "GetPackageItemCommand", MessageType: "GSF.Provider.Landata.Common.V1.Command.GetPackageItemCommand" }) System.IndexOutOfRangeException: Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader. 
>    at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount) 
>    at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count) 
>    at System.IO.TextWriter.SyncTextWriter.Write(Char[] buffer, Int32 index, Int32 count) 
>    at System.Diagnostics.TextWriterTraceListener.WriteLine(String message) 
>    at System.Diagnostics.TraceInternal.WriteLine(String message, String category) 
>    at Nimbus.Configuration.GarbageMan.Add(Object component) 
>    at Nimbus.Infrastructure.NimbusMessagingFactory.CreateQueueSender(String queuePath) 
>    at Nimbus.ConcurrentCollections.ThreadSafeDictionary`2.GetOrAdd(TKey key, Func`2 valueFunc) 
>    at Nimbus.Infrastructure.NimbusMessagingFactory.GetQueueSender(String queuePath) 
>    at Nimbus.Infrastructure.Commands.BusCommandSender.<Deliver>d__c`1.MoveNext()
>

**Comment by ricjac** [comment]
Looks like Log4Net had something similar happen: [Re: Uncaught exception: System.IndexOutOfRangeException](http://mail-archives.apache.org/mod_mbox/logging-log4net-user/200609.mbox/%3C5fca47f10609050652l14efd49ej329bab728e8e70dc@mail.gmail.com%3E)

**Comment by ricjac** [comment]
Checks done:
- The code deployed on the two machines were the same, as it was deployed at the same time with Octopus Deploy.
- Both machines don't have a machine.config file to compare.
- Compared systeminfo.exe output

**Comment by ricjac** [comment]
The issue had occurred on both machines on different days.
The issue seems to have been resolved when we added a proper shutdown procedure.

**Comment by drewfreyling** [comment]
This is still happening and doesn't appear to be anything with the shutdown procedure. I think the tracelisteners need to be thread safe!! - http://stackoverflow.com/questions/1701821/race-condition-textwritertracelistener
